<a href="https://colab.research.google.com/github/divyadn-analytics/SQL-Practice/blob/main/3D_array_5_tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
print(arr[0,1])
print(arr[1,0])
print(arr[0,1,2])
print(arr[1,0,1])
print(arr[1,1,2])
print(arr[1,1,1])
print(arr[1,1,0])
print(arr[1,0,2])
print(arr[0,0,0])



[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[4 5 6]
[7 8 9]
6
8
12
11
10
9
1


In [ ]:
import numpy as np
arr=np.array([
    [[10,20,30],[40,50,60]],[[70,80,90],[100,110,120]]
])
print(arr)
print(arr[0,0,0])
print(arr[0,0,1])
print(arr[0,0,2])
print(arr[0,1,0])
print(arr[0,1,1])
print(arr[0,1,2])
print(arr[1,0,0])
print(arr[1,0,1])
print(arr[1,0,2])
print(arr[1,1,0])
print(arr[1,1,1])
print(arr[1,1,2])

[[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  80  90]
  [100 110 120]]]
10
20
30
40
50
60
70
80
90
100
110
120


In [ ]:
import numpy as np
arr=np.array([
    [[100,200,300],[400,500,600]],[[700,800,900],[1000,2000,3000]]
])
print(arr)
print(arr[0,0,0])
print(arr[0,0,1])
print(arr[0,0,2])
print(arr[0,1,0])
print(arr[0,1,1])
print(arr[0,1,2])
print(arr[1,0,0])
print(arr[1,0,1])
print(arr[1,0,2])
print(arr[1,1,0])
print(arr[1,1,1])
print(arr[1,1,2])


[[[ 100  200  300]
  [ 400  500  600]]

 [[ 700  800  900]
  [1000 2000 3000]]]
100
200
300
400
500
600
700
800
900
1000
2000
3000


In [ ]:
import numpy as np
arr=np.array([
    [[1000,2000,3000],[4000,5000,6000]],[[7000,8000,9000],[10000,20000,30000]]
])
print(arr)
print(arr[0,0,0])
print(arr[0,0,1])
print(arr[0,0,2])
print(arr[0,1,0])
print(arr[0,1,1])
print(arr[0,1,2])
print(arr[1,0,0])
print(arr[1,0,1])
print(arr[1,0,2])
print(arr[1,1,0])
print(arr[1,1,1])
print(arr[1,1,2])


[[[ 1000  2000  3000]
  [ 4000  5000  6000]]

 [[ 7000  8000  9000]
  [10000 20000 30000]]]
1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
20000
30000


In [ ]:
import numpy as np
arr=np.array([
    [[10000,20000,30000],[40000,50000,60000]],[[70000,80000,90000],[100000,200000,300000]]
])
print(arr)
print(arr[0,0,0])
print(arr[0,0,1])
print(arr[0,0,2])
print(arr[0,1,0])
print(arr[0,1,1])
print(arr[0,1,2])
print(arr[1,0,0])
print(arr[1,0,1])
print(arr[1,0,2])
print(arr[1,1,0])
print(arr[1,1,1])
print(arr[1,1,2])


[[[ 10000  20000  30000]
  [ 40000  50000  60000]]

 [[ 70000  80000  90000]
  [100000 200000 300000]]]
10000
20000
30000
40000
50000
60000
70000
80000
90000
100000
200000
300000


In [ ]:
import pandas as pd
dataset={
    "calories":[80,100,110],
    "duration":[10,20,30]
}
myvar=pd.DataFrame(dataset)
print(myvar)

   calories  duration
0        80        10
1       100        20
2       110        30
